include root.mk
include $(MFEXT_HOME)/share/subdir_root.mk
include $(MFCOM_HOME)/share/startup_scripts_profiles.mk

all:: profiles $(PREFIX)/bin/cronwrap.sh $(PREFIX)/bin/mfsysmon.status $(PREFIX)/bin/mfsysmon.start $(PREFIX)/bin/mfsysmon.stop $(PREFIX)/bin/mfsysmon.init load_env
